### PR TITLE
OPENTOK-49309: Change Opentok Version

### PR DESCRIPTION
**Pull request by tnas32**
I changed OpenTok with the latest version. (2.23.1) in OpenTokSDKVersion.rb file

### CODE REVIEW

**Review by pvenum — APPROVED** [review]

**Review by sergioturgil-vonage — APPROVED** [review]
I thought we were in version 2.23.2 but I imagine this is still an outdated SDK, correct?

**Comment by v-kpheng** [comment]
> 

Latest for iOS SDK is 2.23.1 :-)

**Comment by pvenum** [comment]
> I thought we were in version 2.23.2 but I imagine this is still an outdated SDK, correct?

@sergioturgil-vonage  Only windows is 2.23.2

**Comment by sergioturgil-vonage** [comment]
> Latest for iOS SDK is 2.23.1 :-)



> Latest for iOS SDK is 2.23.1 :-)

Ok, I imagined it would be like that. Thx!

**Pull request merged**
