### PR TITLE
Adding link to browser-demo.html

### PR DESCRIPTION
**Pull request by aullman**
Fixing references to browser-demo.html. Sometimes they were referencing browser_demo instead of browser-demo and also adding the link so that people know where the file is.

### CODE REVIEW

**Comment by aullman** [comment]
Actually, @jeffswartz why don't we just link developers to the [OpenTok Playground](https://tokbox.com/developer/tools/playground) for this? It seems like it would be a lot easier for mobile developers. This will let them create a sessionId and token as well. Telling them they have to setup a web server and everything seems like it's a bit much.

**Comment by Lucashuang0802** [comment]
👍

**Comment by Lucashuang0802** [comment]
@aullman Agree with the Playground approach.

**Comment by Lucashuang0802** [comment]
@aullman do you mind fixing the conflict? then we can merge it. thanks

**Comment by Lucashuang0802** [comment]
#35 will do that.

**Pull request closed without merging**
